# Generated by Django 6.0.2 on 2026-02-08 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=150)),
                ('telepon', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('nama_barang', models.CharField(max_length=150)),
                ('stok', models.IntegerField()),
                ('satuan', models.CharField(max_length=50)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.kategori')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.supplier')),
            ],
        ),
    ]
