# Generated by Django 6.0.2 on 2026-02-08 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('tanggal_keluar', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.barang')),
            ],
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.barang')),
            ],
        ),
    ]
